# Generated by Django 4.2.4 on 2024-12-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_album_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.jpg', upload_to='albums/'),
        ),
    ]
