# Generated by Django 5.1.2 on 2024-11-16 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Save_item',
        ),
    ]
