# Generated by Django 5.1.2 on 2024-11-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellign_price',
            new_name='selling_price',
        ),
    ]
