# Generated by Django 5.1.2 on 2024-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
