# Generated by Django 5.1.2 on 2024-11-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
